### ISSUE TITLE
Cannot register user

### ISSUE THREAD

**Issue by kimberlychan1** [kalczugag/Employee-Leave-Management#4]
Hi, thank you so much for creating this system!
I have an issue when trying to register an user.
After I clicked the Register button, I received 400 Bad Request from http://localhost:3000/api/auth/register.
Do you have any idea why would this happen?
Thanks again!

**Comment by kalczugag** [comment]
The error with code 400 occurs when one of the inputs is empty or there is an existing user with the same email.
